// Copyright (c) coherence ApS.
// For all coherence generated code, the coherence SDK license terms apply. See the license file in the coherence Package root folder for more information.

// <auto-generated>
// Generated file. DO NOT EDIT!
// </auto-generated>
namespace Coherence.Generated
{
	using System.Collections.Generic;

	public static class Archetypes
	{
		public const int ExampleCharacter_3b63255ecbc45c94189e0899a9d151a2Index = 0;
		public const int Player_d076185600ad3c7489ff1b08d88bdda7Index = 1;

		public static Dictionary<string, int> IndexForName = new Dictionary<string, int>() {
			{ "ExampleCharacter_3b63255ecbc45c94189e0899a9d151a2", 0 },

			{ "Player_d076185600ad3c7489ff1b08d88bdda7", 1 },

		};
	}
}
